export const brands = [
    { name: "AceBikes", value: "ACEBIKES", warrantyPeriod: null, specialInstructions: null },
    { name: "Akrapovic", value: "AKRAPOVIC", warrantyPeriod: "2Y", specialInstructions: null },
    { name: "Alpinestars", value: "ALPINESTARS", warrantyPeriod: "1Y to 5Y", specialInstructions: "Preferred Solution: REPAIR" },
    { name: "Altrider", value: "ALTRIDER", warrantyPeriod: null, specialInstructions: null },
    { name: "Antigravity Batteries", value: "ANTIGRAVITY BATTERIES", warrantyPeriod: null, specialInstructions: null },
    { name: "Arai", value: "ARAI", warrantyPeriod: "5Y", specialInstructions: null },
    { name: "Arrow", value: "ARROW", warrantyPeriod: null, specialInstructions: null },
    { name: "Artago", value: "ARTAGO", warrantyPeriod: null, specialInstructions: null },
    { name: "ASV Inventions", value: "ASV INVENTIONS", warrantyPeriod: null, specialInstructions: null },
    { name: "Aurora", value: "AURORA", warrantyPeriod: null, specialInstructions: null },
    { name: "AXP Racing", value: "AXP RACING", warrantyPeriod: null, specialInstructions: null },
    { name: "Baja Designs", value: "BAJA DESIGNS", warrantyPeriod: null, specialInstructions: null },
    { name: "Barkbusters Handguards", value: "BARKBUSTERS HANDGUARDS", warrantyPeriod: null, specialInstructions: null },
    { name: "Bartubeless", value: "BARTUBELESS", warrantyPeriod: null, specialInstructions: null },
    { name: "BCD Design", value: "BCD DESIGN", warrantyPeriod: null, specialInstructions: null },
    { name: "Bonamici", value: "BONAMICI", warrantyPeriod: null, specialInstructions: null },
    { name: "Brembo", value: "BREMBO", warrantyPeriod: null, specialInstructions: null },
    { name: "BS Battery", value: "BS BATTERY", warrantyPeriod: "6M", specialInstructions: null },
    { name: "BT Moto", value: "BT MOTO", warrantyPeriod: null, specialInstructions: null },
    { name: "Carpe Iter", value: "CARPE ITER", warrantyPeriod: null, specialInstructions: null },
    { name: "Chigee", value: "CHIGEE", warrantyPeriod: "1Y", specialInstructions: null },
    { name: "CNC Racing", value: "CNC RACING", warrantyPeriod: "1Y", specialInstructions: null },
    { name: "Cool Covers", value: "COOL COVERS", warrantyPeriod: null, specialInstructions: null },
    { name: "D.I.D Chain", value: "D.I.D CHAIN", warrantyPeriod: null, specialInstructions: null },
    { name: "Dainese", value: "DAINESE", warrantyPeriod: null, specialInstructions: null },
    { name: "Denali Electronics", value: "DENALI ELECTRONICS", warrantyPeriod: null, specialInstructions: null },
    { name: "Dimsport", value: "DIMSPORT", warrantyPeriod: null, specialInstructions: null },
    { name: "DNA Filters", value: "DNA FILTERS", warrantyPeriod: "Case to Case Basis", specialInstructions: null },
    { name: "Domino Group", value: "DOMINO GROUP", warrantyPeriod: null, specialInstructions: null },
    { name: "Donner Tech", value: "DONNER TECH", warrantyPeriod: null, specialInstructions: null },
    { name: "Doubletake Mirror", value: "DOUBLETAKE MIRROR", warrantyPeriod: "Case to Case Basis", specialInstructions: null },
    { name: "Ducabike", value: "DUCABIKE", warrantyPeriod: null, specialInstructions: null },
    { name: "Dynaplug", value: "DYNAPLUG", warrantyPeriod: null, specialInstructions: null },
    { name: "Evotech Performance", value: "EVOTECH PERFORMANCE", warrantyPeriod: "1Y", specialInstructions: null },
    { name: "Five Gloves", value: "FIVE GLOVES", warrantyPeriod: "Case to Case Basis", specialInstructions: null },
    { name: "Frey Daytona", value: "FREY DAYTONA", warrantyPeriod: "Manufacturing Defect 3Y, Goretex 2Y", specialInstructions: null },
    { name: "Fullsix Carbon", value: "FULLSIX CARBON", warrantyPeriod: null, specialInstructions: null },
    { name: "Giant Loop", value: "GIANT LOOP", warrantyPeriod: "Case to Case Basis", specialInstructions: null },
    { name: "Gilles Tooling", value: "GILLES TOOLING", warrantyPeriod: null, specialInstructions: null },
    { name: "Globescout", value: "GLOBESCOUT", warrantyPeriod: null, specialInstructions: null },
    { name: "Grip Puppy", value: "GRIP PUPPY", warrantyPeriod: null, specialInstructions: null },
    { name: "Healtech", value: "HEALTECH", warrantyPeriod: null, specialInstructions: null },
    { name: "Helinox", value: "HELINOX", warrantyPeriod: null, specialInstructions: null },
    { name: "Hex Innovate", value: "HEX INNOVATE", warrantyPeriod: null, specialInstructions: null },
    { name: "Ilmberger Carbon", value: "ILMBERGER CARBON", warrantyPeriod: null, specialInstructions: null },
    { name: "Italjet", value: "ITALJET", warrantyPeriod: null, specialInstructions: null },
    { name: "John Doe", value: "JOHN DOE", warrantyPeriod: "5Y", specialInstructions: null },
    { name: "K&N Filters", value: "K&N FILTERS", warrantyPeriod: null, specialInstructions: null },
    { name: "Kellermann", value: "KELLERMANN", warrantyPeriod: null, specialInstructions: null },
    { name: "Klim", value: "KLIM", warrantyPeriod: "Helmets 5Y, Boots 3Y, Heated 2Y, Fading Colors NOT covered, Others indefinite", specialInstructions: null },
    { name: "Koubalinks", value: "KOUBALINKS", warrantyPeriod: null, specialInstructions: null },
    { name: "Kriega", value: "KRIEGA", warrantyPeriod: "10Y", specialInstructions: null },
    { name: "Leatt", value: "LEATT", warrantyPeriod: "Jacket/Pants 5Y, Other 1Y", specialInstructions: null },
    { name: "Lone Rider", value: "LONE RIDER", warrantyPeriod: "2Y", specialInstructions: null },
    { name: "Luimoto", value: "LUIMOTO", warrantyPeriod: null, specialInstructions: null },
    { name: "Malossi", value: "MALOSSI", warrantyPeriod: null, specialInstructions: null },
    { name: "MFW GmbH", value: "MFW GMBH", warrantyPeriod: null, specialInstructions: null },
    { name: "Midland", value: "MIDLAND", warrantyPeriod: null, specialInstructions: null },
    { name: "Motion Pro", value: "MOTION PRO", warrantyPeriod: null, specialInstructions: null },
    { name: "Motogadget", value: "MOTOGADGET", warrantyPeriod: null, specialInstructions: null },
    { name: "Motografix", value: "MOTOGRAFIX", warrantyPeriod: null, specialInstructions: null },
    { name: "Motorex", value: "MOTOREX", warrantyPeriod: null, specialInstructions: null },
    { name: "MRA Windscreens", value: "MRA WINDSHIELDS", warrantyPeriod: null, specialInstructions: null },
    { name: "New Rage Cycles", value: "NEW RAGE CYCLES", warrantyPeriod: "Case to Case Basis", specialInstructions: null },
    { name: "Nonoise Earplugs", value: "NONOISE EARPLUGS", warrantyPeriod: null, specialInstructions: null },
    { name: "Oldtimer", value: "OLDTIMER", warrantyPeriod: null, specialInstructions: null },
    { name: "Outback Motortek", value: "OUTBACK MOTORTEK", warrantyPeriod: null, specialInstructions: null },
    { name: "Overland Fuel", value: "OVERLAND FUEL", warrantyPeriod: null, specialInstructions: null },
    { name: "Parts Europe", value: "PARTS EUROPE", warrantyPeriod: null, specialInstructions: null },
    { name: "Peak Design", value: "PEAK DESIGN", warrantyPeriod: null, specialInstructions: null },
    { name: "Pivot Pegz", value: "PIVOT PEGZ", warrantyPeriod: null, specialInstructions: null },
    { name: "Planet Knox", value: "PLANET KNOX", warrantyPeriod: "Protector Pads 5Y, Others 1Y", specialInstructions: null },
    { name: "Pro-Bolt", value: "PRO-BOLT", warrantyPeriod: null, specialInstructions: null },
    { name: "Quad Lock", value: "QUAD LOCK", warrantyPeriod: "1Y", specialInstructions: null },
    { name: "Qwart", value: "QWART", warrantyPeriod: "2Y", specialInstructions: null },
    { name: "R&G Racing", value: "R&G RACING", warrantyPeriod: "Product Specific", specialInstructions: null },
    { name: "Ram Mounts", value: "RAM MOUNTS", warrantyPeriod: null, specialInstructions: null },
    { name: "Remus", value: "REMUS", warrantyPeriod: null, specialInstructions: null },
    { name: "Rhino USA", value: "RHINO USA", warrantyPeriod: null, specialInstructions: null },
    { name: "Rizoma", value: "RIZOMA", warrantyPeriod: "2Y", specialInstructions: null },
    { name: "Rocky Creek", value: "ROCKY CREEK", warrantyPeriod: "Product Specific", specialInstructions: null },
    { name: "Rok Straps", value: "ROK STRAPS", warrantyPeriod: "1Y", specialInstructions: null },
    { name: "Rokform", value: "ROKFORM", warrantyPeriod: "2Y", specialInstructions: null },
    { name: "Roland Sands", value: "ROLAND SANDS", warrantyPeriod: null, specialInstructions: null },
    { name: "Rotobox", value: "ROTOBOX", warrantyPeriod: null, specialInstructions: null },
    { name: "Rottweiler", value: "ROTTWEILER", warrantyPeriod: null, specialInstructions: null },
    { name: "Rox Speed FX", value: "ROX SPEED FX", warrantyPeriod: null, specialInstructions: null },
    { name: "Rukka", value: "RUKKA", warrantyPeriod: "Gloves/Layers/Accessories/Protectors 2Y, Others 5Y", specialInstructions: "Preferred Solution: REPAIR" },
    { name: "Ruroc", value: "RUROC", warrantyPeriod: "Helmets 3Y, Goggles 2Y, Accessories 2Y", specialInstructions: null },
    { name: "Samcosport", value: "SAMCOSPORT", warrantyPeriod: null, specialInstructions: null },
    { name: "Sargent Cycle", value: "SARGENT CYCLE", warrantyPeriod: null, specialInstructions: null },
    { name: "SBVTools", value: "SBVTOOLS", warrantyPeriod: null, specialInstructions: null },
    { name: "Schroedie", value: "SCHROEDIE", warrantyPeriod: null, specialInstructions: null },
    { name: "Schuberth", value: "SCHUBERTH", warrantyPeriod: "5Y", specialInstructions: null },
    { name: "Scotts Performance", value: "SCOTTS PERFORMANCE", warrantyPeriod: null, specialInstructions: null },
    { name: "Seat Concepts", value: "SEAT CONCEPTS", warrantyPeriod: null, specialInstructions: null },
    { name: "Sena", value: "SENA", warrantyPeriod: "Undefined", specialInstructions: null },
    { name: "Sidi", value: "SIDI", warrantyPeriod: null, specialInstructions: null },
    { name: "SP Connect", value: "SP CONNECT", warrantyPeriod: null, specialInstructions: null },
    { name: "Spidi", value: "SPIDI", warrantyPeriod: null, specialInstructions: null },
    { name: "Sprint Filter", value: "SPRINT FILTER", warrantyPeriod: null, specialInstructions: null },
    { name: "SW Motech", value: "SW MOTECH", warrantyPeriod: null, specialInstructions: null },
    { name: "Tappezzeria Italia", value: "TAPPEZZERIA ITALIA", warrantyPeriod: null, specialInstructions: null },
    { name: "Tecmate", value: "TECMATE", warrantyPeriod: null, specialInstructions: null },
    { name: "Jekill and Hyde", value: "JEKILL AND HYDE", warrantyPeriod: null, specialInstructions: null },
    { name: "The Rokker Company", value: "THE ROKKER COMPANY", warrantyPeriod: null, specialInstructions: null },
    { name: "Tractive", value: "TRACTIVE", warrantyPeriod: null, specialInstructions: null },
    { name: "Tru-Tension", value: "TRU-TENSION", warrantyPeriod: null, specialInstructions: null },
    { name: "TST Industries", value: "TST INDUSTRIES", warrantyPeriod: null, specialInstructions: null },
    { name: "TWM Special Components", value: "TWM SPECIAL COMPONENTS", warrantyPeriod: null, specialInstructions: null },
    { name: "Unit Garage", value: "UNIT GARAGE", warrantyPeriod: null, specialInstructions: null },
    { name: "Uswe", value: "USWE", warrantyPeriod: null, specialInstructions: null },
    { name: "VR46 Valentino Rossi", value: "VR46 VALENTINO ROSSI", warrantyPeriod: null, specialInstructions: null },
    { name: "Wera Tools", value: "WERA TOOLS", warrantyPeriod: null, specialInstructions: null },
    { name: "WRS", value: "WRS", warrantyPeriod: null, specialInstructions: null },
    { name: "Wunderlich", value: "WUNDERLICH", warrantyPeriod: "2Y, Helmets 5Y", specialInstructions: null },
    { name: "Zerofit", value: "ZEROFIT", warrantyPeriod: null, specialInstructions: null }
];

export function renderBrandsDropdown(brands, parentElement, position = "afterbegin") {
        const renderBrands = brands.map(brandDropdownTemplateFn);
    parentElement.insertAdjacentHTML(position, renderBrands.join(""));
}

export function brandDropdownTemplateFn(brand){
    return `<option value="">${brand.name}</option>`;
}

